# NumPy

NumPy stands for Numerical Python !
NumPy is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

## Installation of Numpy 

If you have Anaconda, Install Numpy by going to your terminal or command prompt typing 
#### conda install numpy


or you can also install Numpy on any other ide by going to your command prompt and entering command 
#### pip install numpy

After your installtion is complete lets import Numpy and begin! 

In [4]:
import numpy as np

Checking current Numpy Version 

In [5]:
print(np.__version__)

1.16.2


I will now show you basic numpy use by converting a simple python list into a numpy array

In [6]:
my_list=[10,20,30,40]

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([10, 20, 30, 40])

lets check type of variable arr

In [9]:
type(arr)

numpy.ndarray

## Numpy Array

The array object is called as __ndarray__. We can create ndarray object by using array() function of Numpy libary as you saw in above example.To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

__Dimensions in Array__: A Dimension in arrays is one level of array depth (__nested arrays__). Dimension allows us to access a particluar or group of data.

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d , but we can have more then that! Below I will show you 3-4 arrays with diffrent Number of Dimensions

### 0-D Array 

- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.<br>
Lets create one 0-D Array

In [10]:
arr_0d=np.array(25)

In [11]:
arr_0d

array(25)

Note : 0-D,1-D Arrays are not is our day to day use I am mentioning them just for demonstartion :) 

### 1-D Array <br>
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [12]:
arr_d=np.array([1,2,3,4,5])

In [13]:
arr_d

array([1, 2, 3, 4, 5])

You can directly create a list inside array function ↑ or else you can insert list element ↓

In [14]:
lst1=[1,2,3,4,5]

In [15]:
arr_d=np.array(lst1)

In [16]:
arr_d

array([1, 2, 3, 4, 5])

### 2-D Array <br>
An array that has 1-D arrays as its elements is called a 2-D array.<br>
These are often used to represent matrix or 2nd order tensors

In [17]:
lst2=[[1,2,3],[4,5,6],[7,8,9]]

arr_2d=np.array(lst2)

In [18]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3-D Array <br>
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [19]:
lst3=[[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]]

In [20]:
arr_3d=np.array(lst3)

In [21]:
arr_3d

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

#### Higher Dimension Arrays <br>
An array can have any number of dimensions.<br>
Lets Create an array with 5 Dimensions 

In [22]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)


[[[[[1 2 3 4]]]]]


<br>
NumPy Arrays provides the __ndim__ attribute that returns an integer that tells us how many dimensions the array have.<br>
so lets check ndim for all arrays we created till now 

In [28]:
print('arr_od.ndim  : %s'%(arr_0d.ndim))
print('arr_d.ndim   : %s'%(arr_d.ndim))
print('arr_2d.ndim  : %s'%(arr_2d.ndim))
print('arr_3d.ndim  : %s'%(arr_3d.ndim))
print('arr.ndim     : %s'%(arr.ndim))

arr_od.ndim  : 0
arr_d.ndim   : 1
arr_2d.ndim  : 2
arr_3d.ndim  : 3
arr.ndim     : 5


##### Some Points you need to know about Numpy

- NumPy was created in __2005__ by __Travis Oliphant__. It is an open source project and you can use it freely
- Numpy has functions for working in domain of __linear algebra, fourier transform, and matrices__.
- __Use of Numpy__ : In Python we have lists that serve the purpose of arrays, but they are slow to process.NumPy aims to      provide an array object that is up to 50x faster that traditional Python lists.The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.Arrays are very frequently used in data science, where speed and resources are very important.
- __Whu Numpy is faster then Python List__ : NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.This behavior is called locality of reference in computer science.This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.
- The __source code for NumPy__ is located at this github repository https://github.com/numpy/numpy