NumPy has many built-in Methods which can help in generating arrays lets view some of them!

In [2]:
import numpy as np

### arange

My Personal favourite function is __np.arange()__ 
- NumPy arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it .

numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray

You can get more details about np.arange function by typring __help(np.arange)__ in your notebook/terminal.

Lets Begin !

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(-5,6)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [9]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [20]:
arr = np.arange(5, dtype=float)
print(arr)
print(arr.dtype)
print(type(arr))

[0. 1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [19]:
arr = np.arange(5, dtype=int)
print(arr)
print(arr.dtype)
print(type(arr))

[0 1 2 3 4]
int32
<class 'numpy.ndarray'>


### linspace
- Return evenly spaced numbers over a specified interval.

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

### zeros and ones

- __np.zeros(shape, dtype = None, order = ‘C’)__ : Return a new array of given shape and type, with zeros. 

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- __np.ones(shape, dtype = None, order = ‘C’)__  : Return a new array of given shape and type, with ones.

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### eye

- np.eye(R, C = None, k = 0, dtype = type <‘float’>) : Return a matrix having 1’s on the diagonal and 0’s elsewhere w.r.t. k.
- Creates an __identity matrix__

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random 

__np.random__ again is very popular liabry in python numpy.

What is Random  ? - __Random__ means something that can not be predicted logically.
-Random numbers generated through a generation algorithm are called __pseudo random__.

Lets Begin!

#### rand 
- Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [32]:
np.random.rand(5)

array([0.67198585, 0.25764522, 0.60430154, 0.98943775, 0.66669988])

In [33]:
np.random.rand(3,4)

array([[0.5502644 , 0.94341251, 0.42722544, 0.77858439],
       [0.82432472, 0.73177132, 0.0936621 , 0.60432368],
       [0.39338635, 0.61090425, 0.7682878 , 0.39105741]])

#### randn

- Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [38]:
np.random.randn(3)

array([ 0.21586733,  1.49151307, -0.96751065])

In [39]:
np.random.randn(4,5)

array([[-0.41878583, -2.08280945, -0.30788707, -0.30193485,  1.59370375],
       [ 0.32175279,  1.58447088, -0.52483925, -1.22149818,  2.14446858],
       [ 1.29691538, -0.42007184, -0.01059512,  0.90408688, -0.80213288],
       [ 0.88933538, -0.52358478,  0.42654894,  0.92774633,  1.1014513 ]])

#### randint
- Return random integers from low (inclusive) to high (exclusive).

Confused! Dont worry get detailed information by typing __help(np.random.randint)__ command in your notebook/terminal. :) 

In [40]:
np.random.randint(1,100)

60

In [41]:
np.random.randint(1,100,10)

array([42, 19, 29,  2, 15, 18, 92, 48, 10, 70])

### Reshape 

- Returns an array containing the same data with a new shape.

In [44]:
arr=np.arange(50)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [47]:
arr=np.random.randint(0,50,15)

arr

array([18, 24, 11,  6, 36, 31, 19,  9, 13, 47, 34, 25, 35, 15,  6])

In [49]:
arr.min()

6

In [50]:
arr.max()

47

In [51]:
arr.argmin() 

3

In [53]:
arr.argmax()

9

### Numpy Operations 

You can easily perform array with array arithmetic, or scalar with array arithmetic

In [4]:
arr=np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [11]:
#Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [12]:
#Calcualting exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [13]:
np.max(arr)

10

In [14]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])