### NumPy Array Indexing

- Array indexing is the same as accessing an array element
- You can access an array element by referring to its index number.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [54]:
import numpy as np

#creating a sample array to show indexing 

arr=np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [55]:
arr[2]

2

In [56]:
arr[10]

10

#### getting value in a range

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Broadcasting 

Numpy array are diffent from python list because of its broadcasting feature

In [59]:
arr[5:11]= '20'

arr

array([ 0,  1,  2,  3,  4, 20, 20, 20, 20, 20, 20])

#### Copy()

Note : If you assign a __slice__ of numpy array to another array and make changes in slice , Change will reflect also in orignal array. For this kind of problem Numpy array has copy() function which will not effect orignla one . Let me demonstarte

In [60]:
#Creating Fresh Array 
arr=np.arange(0,101,10)

arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [61]:
slice_of_arr=arr[5:11]

slice_of_arr

array([ 50,  60,  70,  80,  90, 100])

In [62]:
slice_of_arr[:]='50'

slice_of_arr

array([50, 50, 50, 50, 50, 50])

In [63]:
arr

array([ 0, 10, 20, 30, 40, 50, 50, 50, 50, 50, 50])

In [64]:
#Creating Fresh Array 
arr=np.arange(0,101,10)

arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [65]:
arr_copy=arr.copy()

arr_copy

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [66]:
arr_copy[:]=100

arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### Indexing Multidimensional Array 

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**

In [68]:
arr_2d=np.arange(0,25).reshape(5,5)

arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

- pulling out particluar element! like number 16 which is at 3rd row and 1st column 

In [69]:
arr_2d[3][1]

#or 

arr_2d[3,1]

16

In [70]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,3:]

array([[3, 4],
       [8, 9]])

In [71]:
#Shape bottom row
arr_2d[4]

#or

arr_2d[4:,]

array([[20, 21, 22, 23, 24]])

#### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [72]:
#Set up matrix
arr2d = np.zeros((10,10))

In [73]:
#Length of array
arr_length = arr2d.shape[1]

In [74]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [75]:
arr2d[[1,3,5,7]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [76]:
#Allows in any order
arr2d[[7,4,3,2]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

### Selection

Let's check how to use brackets for selection based off of comparison operators.

In [78]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
#when you are using comparsion operators with numpy array you will get an boolean array as 

arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
bool_arr = arr>4

In [82]:
#If you pass a boolean array in arrays arugment you will get only True values

arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [83]:
#you can direct pass comparsion opertor inside an []

arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])